services:
  - type: web
    name: newbb-club
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/newbb.db
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        sync: false
      - key: BARMAN_PASSWORD
        sync: false